apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: {{.Values.metadata.namespace}}
  labels:
    cicd: jenkins
spec:
  selector:
    cicd: jenkins
  ports:
    - name: ui
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: worker
      protocol: TCP
      port: 50000
      targetPort: 50000
  type: {{.Values.service.spec.type}}