apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    cicd: jenkins
  annotations:
      "helm.sh/hook": "pre-install"
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"