apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: database
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: pgadmin-configmap
              key: pgadmin-default-email
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: pgadmin-default-password
        volumeMounts:
        - name: pgadmin-pv
          mountPath: /var/lib/pgadmin
        resources:
              requests:
                memory: "1024Mi"
              limits:
                memory: "1024Mi"
      volumes:
      - name: pgadmin-pv
        persistentVolumeClaim:
          claimName: pgadmin-pvc