apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    cicd: jenkins
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"