apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: cicd
  labels:
    cicd: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-m2-cache
  namespace: cicd
  labels:
    cicd: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-cache
  namespace: cicd
  labels:
    cicd: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi