apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: {{.Values.metadata.namespace}}
  labels:
    db: mariadb
spec:
  selector:
    db: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: {{.Values.service.spec.type}}