apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: {{.Values.metadata.namespace}}
  labels:
    db: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mariadb
  template:
    metadata:
      labels:
        db: mariadb
    spec:
      containers:
      - name: mariadb
        image: {{.Values.image.repository}}:{{.Values.image.tag}}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password
        volumeMounts:
        - name: mariadb-pv
          mountPath: /var/lib/mysql
        resources:
              requests:
                memory: "1024Mi"
              limits:
                memory: "1024Mi"
      volumes:
      - name: mariadb-pv
        persistentVolumeClaim:
          claimName: mariadb-pvc