apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: {{.Values.metadata.namespace}}
  labels:
    db: mariadb
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data:
  mariadb-user: x
  mariadb-root-password: x
  mariadb-replication-password: x
  mariadb-password: x