apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus-server
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi