apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: database
  labels:
    db: postgres
spec:
  selector:
    db: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001
  type: NodePort