apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: database
  labels:
    db: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        volumeMounts:
        - name: postgres-pv
          mountPath: /var/lib/postgresql/data
        resources:
              requests:
                memory: "2048Mi"
              limits:
                memory: "2048Mi"
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgres-pvc